"""
LANGUAGE AS A CARRIER; BOOLEAN AS ITS ZERO-LOAD LIMIT.

Three claims are separated here because they fare differently.

  A. "subject-verb-object IS (V, G, theta)"      -> FALSE, level mismatch
  B. "language and mathematics share a structure" -> HOLDS, as shape
  C. "boolean is stripped subject-predication"    -> HOLDS, strongest

A sentence is a PROPAGATION: subject / verb -> object is P / G -> Q.
A language is a CARRIER: lexicon = V, verb inventory = G, parse budget
= theta. Those are different levels, and conflating them is what makes
claim A fail.

Running this file IS its audit.
"""
import json, os, sys
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from claims import Suite

# ── language as a carrier ─────────────────────────────────────────────
LEXICON = ("the rat", "the cat", "the dog", "the man", "the boy")
VERBS   = ("ate the malt", "killed", "chased", "startled", "saw")


def centre_embed(depth):
    """One rule, applied recursively. Grammaticality is flat across depth."""
    s = LEXICON[0]
    for i in range(1, depth + 1):
        s += " " + LEXICON[i]
    for i in range(depth, 0, -1):
        s += " " + VERBS[i]
    return s + " " + VERBS[0]


def open_dependencies(depth):
    """Peak subjects awaiting a verb. Each unresolved subject is a
    distinction held open at cost. This is the load."""
    return depth + 1


# ── predication, loaded and stripped ──────────────────────────────────
class Predication:
    """'X is P' with its scope intact."""
    __slots__ = ("s", "p", "degree", "scope")
    def __init__(self, s, p, degree, scope):
        self.s, self.p, self.degree, self.scope = s, p, degree, dict(scope)

    def strip(self):
        """Threshold the degree, discard every scope dimension.
        The result IS the boolean."""
        return self.degree >= 0.5


def loaded_and(a, b):
    """(degree, load, scope) — degrees meet, loads add, scopes union."""
    return (min(a[0], b[0]), a[1] + b[1], a[2] | b[2])


def audit():
    S = Suite("GRAMMAR — language as carrier, boolean as its L=0 limit",
              __file__)

    # ---- A. the level mismatch, made explicit
    S.add("SVO IS NOT (V, G, theta): V/G/theta specify a carrier; S/V/O are "
          "slots in one utterance. theta is a budget and an object is not a "
          "budget. The mapping that holds is to the OPERATOR: subject = P, "
          "verb = G, object = Q",
          True, 1, None, False,
          "exhibit a reading on which an object functions as a processing "
          "budget rather than as an outcome", derived=True)

    # ---- B. a real, measurable theta in language
    DEPTHS = range(0, 5)
    flat_rule = all(centre_embed(d).count("the") == d + 2 for d in DEPTHS)
    monotone_load = all(open_dependencies(d) < open_dependencies(d + 1)
                        for d in list(DEPTHS)[:-1])
    S.add("LANGUAGE HAS A THRESHOLD DISTINCT FROM ITS RULE: centre-embedding "
          "is generated by one rule applied recursively, so grammaticality "
          "is flat across depth, while peak open dependencies grow "
          "monotonically. The rule permits what the budget refuses",
          flat_rule and monotone_load, len(DEPTHS), len(DEPTHS), True,
          "exhibit a centre-embedding depth where the generating rule "
          "changes, or where open dependencies do not increase with depth",
          f"depths {DEPTHS.start}..{DEPTHS.stop - 1}")
    S.seal({"stage": "theta", "depths": list(DEPTHS)})

    # ---- C. boolean as the zero-load limit
    CASES = [
        Predication("this house", "expensive", 0.62,
                    {"postcode": "SE15", "quarter": "2026Q2",
                     "deflator": "ONS HPI", "reference": "median local income",
                     "baseline": "2019"}),
        Predication("the economy", "healthy", 0.48,
                    {"measure": "GDP", "boundary": "SNA production boundary",
                     "excluded": "unpaid household work, >25% of GDP",
                     "distribution": "not represented"}),
        Predication("this wage", "fair", 0.50,
                    {"basket": "CPI 2026", "hours": "contracted not worked",
                     "recovery cost": "unpriced", "alternatives": "one"}),
    ]
    all_erase = all(len(c.scope) > 0 and isinstance(c.strip(), bool)
                    for c in CASES)
    tie = [c for c in CASES if c.degree == 0.5]
    S.add("STRIPPING PREDICATION YIELDS A BOOLEAN: every case returns a bare "
          "truth value while discarding every scope dimension it carried",
          all_erase, len(CASES), len(CASES), True,
          "exhibit a loaded predication whose stripped form retains a scope "
          "dimension", "three worked predications")
    S.add("THE ONE-HALF TEST FIRES: a predication at degree exactly 0.5 still "
          "returns a definite boolean, because a threshold must break the "
          "tie in some direction — which is the suppressed continuity made "
          "visible", len(tie) == 1 and isinstance(tie[0].strip(), bool),
          1, 1, True,
          "exhibit a degree-0.5 predication whose stripped form abstains",
          "the wage case")

    PAIRS = [((0.9, 3, {"a"}), (0.8, 2, {"b"})),
             ((0.6, 1, {"c"}), (0.4, 5, {"d"})),
             ((1.0, 0, frozenset()), (1.0, 0, frozenset())),
             ((0.5, 2, {"e"}), (0.5, 2, {"f"})),
             ((0.2, 7, {"g"}), (0.95, 1, {"h"}))]
    agree = all((loaded_and(a, b)[0] >= 0.5)
                == ((a[0] >= 0.5) and (b[0] >= 0.5)) for a, b in PAIRS)
    zero = [(a, b) for a, b in PAIRS if a[1] == 0 and b[1] == 0]
    S.add("BOOLEAN IS THE L=0 LIMIT, NOT A RIVAL SYSTEM: stripped loaded "
          "conjunction agrees with boolean AND on every pair; the difference "
          "is that the loaded form still knows its cost and scope",
          agree, len(PAIRS), len(PAIRS), True,
          "exhibit a pair where stripped loaded conjunction and boolean AND "
          "disagree", "five conjunction pairs")
    S.add("AT ZERO LOAD WITH EMPTY SCOPE THE TWO ARE INDISTINGUISHABLE — "
          "which is the precise sense in which boolean is not wrong, only "
          "unpriced", len(zero) >= 1, len(zero), len(zero), True,
          "exhibit a zero-load empty-scope pair where the loaded form "
          "carries information the boolean lacks", "the unloaded pair",
          derived=True)
    S.seal({"stage": "boolean", "pairs": len(PAIRS)})

    S.nonclaim("NOT claimed: that the psycholinguistic breakdown depth is "
               "established here. This suite shows a rule/budget SEPARATION; "
               "the empirical value of the threshold is external to it and "
               "is not measured.")
    S.nonclaim("NOT claimed: that all languages impose the same cut. SVO and "
               "SOV differ in surface order while plausibly sharing the cut, "
               "but ergative-absolutive alignment is a live test this suite "
               "does not run.")
    S.nonclaim("NOT claimed: that degrees in the worked predications are "
               "measurements. They are illustrative values chosen to expose "
               "the stripping operation, including the deliberate tie.")
    S.nonclaim("NOT claimed: that boolean logic is mistaken. It is the L=0 "
               "idealisation of predication — useful, and silent about what "
               "it cost.")
    return S


if __name__ == "__main__":
    S = audit()
    S.report()
    here = os.path.dirname(os.path.abspath(__file__))
    with open(os.path.join(here, "manifests", "grammar_manifest.json"), "w") as f:
        json.dump(S.manifest(), f, indent=2, sort_keys=True)
    sys.exit(1 if S.failed() else 0)
